name: sikomti_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.8
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.6.0
  path_provider: ^2.1.5
  universal_html: ^2.0.5
  file_picker: ^5.0.0
  url_launcher: ^6.0.20 # Add this line
  permission_handler: ^10.2.0 # Add this line
  html: ^0.15.0  # Add this line
  universal_io: ^2.0.4
  open_filex: ^4.5.0
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_web_plugins:
  sdk: flutter

flutter:
  uses-material-design: true
  assets :
    - assets/image/logomhs.png
    - assets/image/profile.png
    - assets/image/home.png
    - assets/image/LOGO.png
    - assets/image/polinema-bw.png
    - assets/image/logonew.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
